### ISSUE TITLE
sublime text3不起作用，求各位帮忙解决一下

### ISSUE THREAD

**Issue by Shanlikai** [flashlizi/cssrem#25]
前面提到的方法都以操作过，都不行

**Comment by keysey** [comment]
在自动转换的时候不行吗？

**Comment by Shanlikai** [comment]
完全不起作用，PC笔记本的sublime3都不行。

**Comment by keysey** [comment]
https://github.com/keysey/cssrem 你看我这个补充了这个作者设置步骤，你看对你有用没

**Comment by Shanlikai** [comment]
可以了，多谢，就是少了这个JS设置。
https://github.com/flashlizi/cssrem
在这里完全没有说，你怎么找到的。。。

**Comment by keysey** [comment]
有用就好，我以为你是设置问题，谁知道是js代码没有设置

**Comment by Shanlikai** [comment]
厉害了我的姐，补充设置很关键。

**Comment by keysey** [comment]
https://segmentfault.com/a/1190000004524243 这个有讲适配问题，共同学习
